// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGg1oEA1TlvHW2umEh-ofkXKcoaKYoKps',
    appId: '1:702257031837:web:13e76efb833522f4b18274',
    messagingSenderId: '702257031837',
    projectId: 'event-planning-2cd34',
    authDomain: 'event-planning-2cd34.firebaseapp.com',
    storageBucket: 'event-planning-2cd34.firebasestorage.app',
    measurementId: 'G-1G0TLERBQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGdBAdwR5u0g_IPPPVQ6heOM8oDIw9wEM',
    appId: '1:702257031837:android:e9706fe33e0938bbb18274',
    messagingSenderId: '702257031837',
    projectId: 'event-planning-2cd34',
    storageBucket: 'event-planning-2cd34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgrkbIB9ozNb0_j1D5jY_fk6-9ilSxHYI',
    appId: '1:702257031837:ios:b3fa0755dd6cacccb18274',
    messagingSenderId: '702257031837',
    projectId: 'event-planning-2cd34',
    storageBucket: 'event-planning-2cd34.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgrkbIB9ozNb0_j1D5jY_fk6-9ilSxHYI',
    appId: '1:702257031837:ios:b3fa0755dd6cacccb18274',
    messagingSenderId: '702257031837',
    projectId: 'event-planning-2cd34',
    storageBucket: 'event-planning-2cd34.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGg1oEA1TlvHW2umEh-ofkXKcoaKYoKps',
    appId: '1:702257031837:web:f5df42052ea4a9cbb18274',
    messagingSenderId: '702257031837',
    projectId: 'event-planning-2cd34',
    authDomain: 'event-planning-2cd34.firebaseapp.com',
    storageBucket: 'event-planning-2cd34.firebasestorage.app',
    measurementId: 'G-ZR4Q2KVZ0Y',
  );

}